CREATE TYPE [dbo].[ImportArticleStructure] AS TABLE
(
	[ArticleID]			NVARCHAR(50) NOT NULL,
	[ArticleTitle]		NVARCHAR(200) NULL,
	[ArticleSubtitle]	NVARCHAR(256) NULL,
	[CoverImage]		NVARCHAR(256) NULL,
	[AllowComent]		NVARCHAR(50) NULL,
	[Visits]			INT NULL,
	[ArticleStatus]		NVARCHAR(50) NULL,
	[OverdueTime]		DATETIME NULL,
	[HtmlContent]		NVARCHAR(max) NULL,
	[TextContent]		TEXT NULL,
	[VisitRights]		NVARCHAR(256) NULL,
	[Keyword]			NVARCHAR(100) NULL,
	[ArticleType]		NVARCHAR(50) NULL,
	[ArticleTime]		DATETIME NULL,
	[ArticleWriter]		NVARCHAR(50) NULL,
	[ArticleSourceName] NVARCHAR(50) NULL,
	[ArticleSource]		NVARCHAR(256) NULL,
	[IsDeleted]			BIT NULL,
	[VersionNo]			INT NULL,
	[TransactionID]		NVARCHAR(50) NULL,
	[CreatedBy]			NVARCHAR(50) NULL,
	[CreatedTime]		DATETIME NULL,
	[LastUpdatedBy]		NVARCHAR(50) NULL,
	[LastUpdatedTime]	DATETIME NULL,
	[ArticleVisit]		INT NULL,
	[IsAnswer]			INT NULL,
	[MappingID]			NVARCHAR(50) NOT NULL,
	[SvrID]				NVARCHAR(50) NOT NULL,
	[AppID]				NVARCHAR(50) NOT NULL,
	[ChannelID]			NVARCHAR(50) NOT NULL,	
	[Summary]			NVARCHAR(2000) NULL,
	[Images]			NVARCHAR(2000) NULL,	
	[Category]			NVARCHAR(50) NOT NULL,
	[OpenStyle]			NVARCHAR(50) NULL,
	[Url]				NVARCHAR(1000) NOT NULL,	
	[PublishUserName]	NVARCHAR(50) NULL
);
